### ISSUE TITLE
Blog theme

### ISSUE THREAD

**Issue by LtECoD** [MichielStock/michielstock.github.io#4]
Hi, I am very interested in your blog theme. Could your share this theme, or tell me the theme name. 
Thanks

**Comment by MichielStock** [comment]
Hi, i feel flattered, but this is a very standard template. I use [Franklin](https://franklinjl.org/) to build my blog and the theme is "tufte": https://github.com/tlienart/FranklinTemplates.jl

Check out these templates:
https://tlienart.github.io/FranklinTemplates.jl/

**Comment by MichielStock** [comment]
(though I did make the background whiter)

**Comment by LtECoD** [comment]
Perfect!
